import React from 'react';
import {
  ClockCircleOutlined,
  MessageOutlined,
  ThunderboltOutlined,
  GlobalOutlined,
  FileTextOutlined,
  ApiOutlined,
  DatabaseOutlined,
  RobotOutlined,
  HourglassOutlined,
  BranchesOutlined,
  RetweetOutlined,
  SyncOutlined,
  SettingOutlined,
  SearchOutlined,
  FileAddOutlined,
  SendOutlined,
  SaveOutlined,
  HistoryOutlined,
  PlayCircleOutlined,
  ExportOutlined,
  ApartmentOutlined,
  EditOutlined,
  CloudOutlined,
  CloudUploadOutlined,
  CloudDownloadOutlined,
} from '@ant-design/icons';

export const NODE_ICONS = {
  schedule: <ClockCircleOutlined style={{ color: '#52c41a' }} />,
  notification: <MessageOutlined style={{ color: '#1890ff' }} />,
  click: <ThunderboltOutlined style={{ color: '#faad14' }} />,
  log: <FileTextOutlined style={{ color: '#595959' }} />,
  webhook: <ApiOutlined style={{ color: '#eb2f96' }} />,
  dataChange: <DatabaseOutlined style={{ color: '#fa8c16' }} />,
  aiAgent: <RobotOutlined style={{ color: '#13c2c2' }} />,
  waitUpdate: <HourglassOutlined style={{ color: '#faad14' }} />,
  if: <BranchesOutlined style={{ color: '#eb2f96' }} />,
  while: <RetweetOutlined style={{ color: '#722ed1' }} />,
  for: <SyncOutlined style={{ color: '#2f54eb' }} />,
  fetchResource: <SearchOutlined style={{ color: '#faad14' }} />,
  dingTalkRobot: <SendOutlined style={{ color: '#007fff' }} />,
  capability: <ThunderboltOutlined style={{ color: '#faad14' }} />,
  skillAction: <RobotOutlined style={{ color: '#eb2f96' }} />,
  skillNode: <ThunderboltOutlined style={{ color: '#722ed1' }} />,
  ensureConvo: <MessageOutlined style={{ color: '#1890ff' }} />,
  addMessage: <MessageOutlined style={{ color: '#52c41a' }} />,
  fetchMemory: <HistoryOutlined style={{ color: '#52c41a' }} />,
  persistMsg: <SaveOutlined style={{ color: '#595959' }} />,
  sendSseEvent: <ThunderboltOutlined style={{ color: '#eb2f96' }} />,
  buildAnalysisQuery: <SettingOutlined style={{ color: '#fa8c16' }} />,
  mongoAggregate: <PlayCircleOutlined style={{ color: '#52c41a' }} />,
  recallKnowledge: <DatabaseOutlined style={{ color: '#fa8c16' }} />,
  vectorIndex: <DatabaseOutlined style={{ color: '#fa8c16' }} />,
  vectorSearch: <SearchOutlined style={{ color: '#1677ff' }} />,
  fetchMemorySection: <FileTextOutlined style={{ color: '#52c41a' }} />,
  upsertMemorySection: <EditOutlined style={{ color: '#722ed1' }} />,
  loadMemory: <HistoryOutlined style={{ color: '#722ed1' }} />,
  getExecutionLogs: <HistoryOutlined style={{ color: '#13c2c2' }} />,
  getMemoryHeaders: <DatabaseOutlined style={{ color: '#eb2f96' }} />,
  readUserProperty: <CloudDownloadOutlined style={{ color: '#1677ff' }} />,
  writeUserProperty: <CloudUploadOutlined style={{ color: '#52c41a' }} />,
  end: <ExportOutlined style={{ color: '#ff4d4f' }} />,
  default: <SettingOutlined />,
};

export const STANDARD_SYSTEM_INPUTS = [
  {
    name: 'orgId',
    label: '组织 ID',
    type: 'string',
    required: false,
    isSystem: true,
    description: 'Organization identifier',
  },
  {
    name: 'appId',
    label: '应用 ID',
    type: 'string',
    required: false,
    isSystem: true,
    description: 'Application identifier',
  },
  {
    name: 'userId',
    label: '用户 ID',
    type: 'string',
    required: false,
    isSystem: true,
    description: 'Actor user ID',
  },
  {
    name: 'sessionId',
    label: 'Session ID',
    type: 'string',
    required: false,
    isSystem: true,
    description: 'Web session identifier',
  },
  {
    name: 'sessionName',
    label: '会话名称',
    type: 'string',
    required: false,
    isSystem: true,
    description: 'Display name of the session',
  },
];
