// 中文注释: 统一错误码常量。便于后续前端根据 code 做精细化提示与国际化。
// 命名规范: 领域前缀 + 语义，例如 AI_INTENT_PARSE_FAIL。
export const ERROR_CODES = {
  OK: 'OK',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  // AI 相关
  AI_INTENT_PARSE_FAIL: 'AI_INTENT_PARSE_FAIL',
  AI_MODEL_INVOKE_FAIL: 'AI_MODEL_INVOKE_FAIL',
  AI_CHART_RECOMMEND_FAIL: 'AI_CHART_RECOMMEND_FAIL',
  AI_STREAM_INTERRUPTED: 'AI_STREAM_INTERRUPTED',
  AI_USER_INPUT_REQUIRED: 'AI_USER_INPUT_REQUIRED',
  AI_QUERY_GENERATION_FAIL: 'AI_QUERY_GENERATION_FAIL',
  AI_SCHEMA_NOT_FOUND: 'AI_SCHEMA_NOT_FOUND',
  AI_UNSUPPORTED_OPERATOR: 'AI_UNSUPPORTED_OPERATOR',
  // 工作流相关
  WORKFLOW_VALIDATION_FAIL: 'WORKFLOW_VALIDATION_FAIL',
};
