/**
 * 系统资源相关事件常量
 */
export const RESOURCE_EVENTS = {
  UPDATED: 'RESOURCE_UPDATED',
  CREATED: 'RESOURCE_CREATED',
  DELETED: 'RESOURCE_DELETED',
};

export const WORKFLOW_EVENTS = {
  NODE_STARTED: 'NODE_STARTED',
  NODE_FINISHED: 'NODE_FINISHED',
  WORKFLOW_FINISHED: 'WORKFLOW_FINISHED',
};
